services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      timeout: 3s
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env
    environment:
      CONNECTION_STRING: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
    ports:
    - "8080:8080"
  webapp:
    build:
      context: ./pog-tma
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./pog-tma:/src"
      - "/src/node_modules"
    environment:
      - NODE_ENV=development

volumes:
  pg_data: