services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./web/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/lestencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email rahman.i@mail.ru -d potential-octo-goggles.ru --agree-tos

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      timeout: 3s

  math:
    container_name: math
    build:
      context: ./math
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: .env
    environment:
      CONNECTION_STRING: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
      MATH_SERVICE_URL: "http://math:8000"
    expose:
      - "8080"
    depends_on:
      - postgres
      - math

volumes:
  pg_data:
