services:
  webapp:
    build:
      context: ./pog-tma
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./pog-tma:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
