FROM golang:1.24.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o migrate ./cmd/migrate

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/migrate .
COPY --from=builder /app/migrations ./migrations

RUN ls -la /app/migrations
CMD ./migrate "$CONNECTION_STRING" up