FROM golang:latest AS builder

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o server ./cmd/api

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./server"]