name: Deploy project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /home/${{secrets.SSH_USER}}/project
            echo "Pulling latest changes..."
            git pull origin main

            echo "Rebuilding and restarting containers..."
            docker compose down
            docker compose pull
            docker compose up -d --build

            echo "Cleaning up old Docker images..."
            docker system prune -af