name: Deploy project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build web
        working-directory: ./web
        run: |
          npm i
          npm run build

      - name: Deploy static to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/***/project/web/dist/*
            scp -r -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER}}/project/web/dist/

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /home/${{secrets.SSH_USER}}/project
            echo "Pulling latest changes..."
            git pull origin main

            echo "Rebuilding and restarting containers..."
            docker compose down
            docker compose pull
            docker compose -f ./docker-compose.prod.yaml up -d --build

            echo "Cleaning up old Docker images..."
            docker system prune -af