name: Deploy project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            echo "Delete old static"
            rm -rf /home/${{ secrets.SSH_USER }}/project/web/dist
            mkdir -p /home/${{ secrets.SSH_USER }}/project/web/dist

            echo "Updating repo"
            cd /home/${{secrets.SSH_USER}}/project
            git stash
            git pull origin main

            echo "Building static files"
            cd ./web
            npm i
            npm run build

            cd /home/${{secrets.SSH_USER}}/project
            echo "Rebuilding and restarting containers"
            docker compose -f docker-compose.prod.yaml down
            docker compose -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.prod.yaml up --build -d

            echo "Cleaning up"
            docker system prune -af

